### ISSUE TITLE
the docker compose will deploy this on a single VM?

### ISSUE THREAD

**Issue by Dhruv-Garg79** [mr-karan/clickhouse-keeper-example#5]
Even though we are running 4 nodes, are they running on a single EC2 VM, since you are using docker compose in the example?
In the actual production environment, was this the case?

would love to know more details of the final production setup.

**Comment by mr-karan** [comment]
This repo is only a local setup env of how Clickhouse clusters can run. 4 containers on a single VM are used for demonstration purposes. In prod, that would be a multi AZ distributed node setup, each node running just one process of clickhouse-server.
